Fix to try and resolve module version mismatch on Mac.
https://github.com/kexplo/electron-edge/issues/18

A JavaScript error occurred in the main process
Error: Module version mismatch. Expected XX, got YY.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

- When executing the install script this will try to work out the version of electron that is installed and when executing the node-gyp on Mac will pass the --target=version to the build build process.
- This only affects the Mac installation as I do not have a Linux to test with.

- Without this change one would have rebuild the Native Modules as outlined in issue https://github.com/kexplo/electron-edge/issues/18
- Since this tries to resolve electron this seemed to be the best place for the change instead of in the Edge project.